name: cli
description: >
  A command line application that can be compiled to native code using
  dart2native.

# this is example cli app
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  build_cli_annotations: ^2.0.0
  github: ^8.0.1
  intl: ^0.17.0

dev_dependencies:
  build_cli: ^2.0.0
  build_runner: ^2.0.6
  lints: ^1.0.0
  test: ^1.6.0

executables:
  cli: cli
